### PR TITLE
Automated script to run all predicates at once and post to NGROK

### PR DESCRIPTION
**Pull request by timstackblock**
### Description 
Creating automated test for chainhooks to run all predicates at once both Post and File append so the data can be validated.

# automate-chainhooks
automate-chainhooks is a node script for running the chainhooks predicate.

### Prerequisites

- npm installed and Node v16.*
- [ngrok](https://dev.to/ibrarturi/how-to-test-webhooks-on-your-localhost-3b4f)
- [chainhook](https://github.com/hirosystems/chainhook/blob/5791379655fba786abf6e265311c0d789a8722e5/docs/getting-started.md)

### Run script
1. Go to the root of the project and do `npm install`. Make sure you have satisfied the above Prerequisites.
2. Start ngrok using the command `ngrok http 127.0.0.1:3009`. Once it starts, provide the ngrok URL in the `.env` file for `DOMAIN_URL`. This is required to post the result for the http predicates. You can check the ngrok requests at `localhost:4040`
3. Run all the predicates:
    ```sh
    $ npm run predicates
4. Run all the file result predicates:
    ```sh
    $ npm run file-predicates
5. Run all the POST URL predicates:
    ```sh
    $ npm run post-predicates
6. Clear all the result files:
    ```sh
    $ npm run clear-result-files
7. Run transaction predicate for file append and POST
    ```sh
    $ predicate=transaction npm run predicates
8. Run print-event predicate for file append and POST
    ```sh
    $ predicate=print-event npm run predicates
9. Run nft-event predicate for file append and POST
    ```sh
    $ predicate=nft-event npm run predicates
10. Run ft-event predicate for file append and POST
    ```sh
    $ predicate=ft-event npm run predicates
11. Run contract-deployment predicate for file append and POST
    ```sh
    $ predicate=contract-deployment npm run predicates
12. Run contract-call predicate for file append and POST
    ```sh
    $ predicate=contract-call npm run predicates
13. Run block-height predicate for file append and POST
    ```sh
    $ predicate=block-height npm run predicates
14. Run stx-event predicate for file append and POST
    ```sh
    $ predicate=stx-event npm run predicates

#### Breaking change?

N/A



---

### Checklist

- [ ] All tests pass
- [ ] Tests added in this PR (if applicable)

### CODE REVIEW

**Comment by MicaiahReid** [comment]
@timstackblock This is so awesome! I'm really happy to see this sort of testing being done. I will get into reviewing the details of this PR early in the week, but I have some big picture questions.
 1. I'm curious if it would be possible and if there are any potential downsides of having this in a separate repo. Could we still get the same value out of the tests if they were still in a separate repo? I'm curious about this because this repo will also have end to end tests and some integration tests written in rust, and introducing a whole separate folder structure and language with its own set of dependencies seems like it could become a lot for Chainhook to manage. Let me know if you (or @lgalabru if you) have any thoughts.
 2. I see that this will trigger a series of predicates - do we currently have any assertions on the actual results of the predicates? Or is that planned for the next iteration?

**Comment by timstackblock** [comment]
@MicaiahReid thanks for the reply. I can move these to a separate repo if this works better for the team. I'm pretty flexible just let me know what works better for you guys. And yes you are correct the assertions will be coming in my next push I will most likely have to add some webdriver framework to assert on POST that are pushed to ngrok. I moved from a webhooks testing site to ngrok and localhost for that reason so we don't have to worry about a 3rd party site, that will be coming soon. I appreciate the feedback!

**Comment by MicaiahReid** [comment]
I'd be interested in hearing @lgalabru's thoughts on keeping here vs another repo.

**Comment by lgalabru** [comment]
I'd be in favor of optimizing for @timstackblock productivity, at least for now? We could revisit later, once we have more unit tests and more confidence?
@timstackblock Could we add a sub-README explaining how to use these tests? The description of this PR would do just fine.

**Comment by timstackblock** [comment]
@lgalabru sure no problem I can add that

**Comment by timstackblock** [comment]
@lgalabru Here is the sub read.me that is in the automate folder. To run the test just follow the steps below to setup your ngrok URL on port 3006. I have change the package.json file to make npm run predicates run individual test right now it is set to run the contract-call test. You can set it to run the contract-deploy, test and the transaction test as well. The bug I posted here https://github.com/hirosystems/chainhook/issues/352 and the other related bugs are causing failures on the Block-hieght test, ft-events, nft-events, print-events, stx-events predicates as the data that comes back is incorrect.

I also noticed that on the contract call predicate the post and file append with the same exact predicate bring back different data. I will create separate bug for this as well.

# automate-chainhooks
automate-chainhooks is a npm script for automation testing of [chainhook](https://github.com/hirosystems/chainhook/blob/5791379655fba786abf6e265311c0d789a8722e5/docs/getting-started.md)

### Prerequisites
- npm installed and Node v16.*
- [ngrok](https://dev.to/ibrarturi/how-to-test-webhooks-on-your-localhost-3b4f)
- [chainhook](https://github.com/hirosystems/chainhook/blob/5791379655fba786abf6e265311c0d789a8722e5/docs/getting-started.md)
- [zeromq] (https://zeromq.org/download/)


### Run script
1. Go to the root of the project and do `npm install`. Make sure you have satisfied the above Prerequisites.
2. Start ngrok using the command `ngrok http 3006`. Once it starts, copy the ngrok URL into the `.env` file for `DOMAIN_URL`. This is required to post the result for the http predicates example of the ngrok URL https://1f67-37-19-198-81.ngrok.io/. You can check the ngrok requests at `localhost:4040`
3. Run all the predicates:
    ```sh
    $ npm run predicates
4. Run all the file result predicates:
    ```sh   
    $ npm run file-predicates
5. Run all the POST URL predicates:
    ```sh
    $ npm run post-predicates
6. Clear all the result files:
    ```sh
    $ npm run clear-result-files
7. Run transaction predicate for file append and POST
    ```sh
    $ predicate=transaction npm run predicates
8. Run print-event predicate for file append and POST
    ```sh
    $ predicate=print-event npm run predicates
9. Run nft-event predicate for file append and POST
    ```sh
    $ predicate=nft-event npm run predicates
10. Run ft-event predicate for file append and POST
    ```sh
    $ predicate=ft-event npm run predicates
11. Run contract-deployment predicate for file append and POST
    ```sh
    $ predicate=contract-deployment npm run predicates
12. Run contract-call predicate for file append and POST
    ```sh
    $ predicate=contract-call npm run predicates
13. Run block-height predicate for file append and POST
    ```sh
    $ predicate=block-height npm run predicates
14. Run stx-event predicate for file append and POST
    ```sh
    $ predicate=stx-event npm run predicates

**Comment by lgalabru** [comment]
I don't know yet how we will be able to use this automation scripts, but it feels like a lot of work went into this.
I've moved all the files from `/automate` to `/tests/integration-tests`.

**Pull request merged**
