### PR TITLE
Updated note and tip format

### PR DESCRIPTION
**Pull request by LakshmiLavanyaKasturi**
Fixed note and tip formats to render correctly on the docs repo.

### CODE REVIEW

**Comment by LakshmiLavanyaKasturi** [comment]
@MicaiahReid Please review. Thanks!

**Review by MicaiahReid — CHANGES_REQUESTED** [review]
Hey @LakshmiLavanyaKasturi! Do you know what the formatting is supposed to look like for text wrapped in`:::note :::`? It doesn't seem to be rendering when I view the file in github:
Screenshot 2023-07-23 at 1 50 43 PM

**Comment by LakshmiLavanyaKasturi** [comment]
> Hey @LakshmiLavanyaKasturi! Do you know what the formatting is supposed to look like for text wrapped in`:::note :::`? It doesn't seem to be rendering when I view the file in github: Screenshot 2023-07-23 at 1 50 43 PM

I tested this by pulling these changes to docs repo and the preview looks like this: 
image

**Comment by MicaiahReid** [comment]
Ahh I think I know what's happening, @LakshmiLavanyaKasturi.

The `:::note` tag works on the website docs, but it doesn't work in the Github markdown renderer :(

Since many developers use the Github markdown for documentation, I think we'll need to make sure all markdown correctly renders on both. Do you know if it will be possible to render a note with the same formatting _without_ using that `:::note` tag?

**Comment by LakshmiLavanyaKasturi** [comment]
Closing this PR in favor of https://github.com/hirosystems/chainhook/pull/373 as this PR got lot of merge conflicts with remote doc changes.

**Pull request closed without merging**
