### PR TITLE
fix: op_return predicate evaluation

### LINKED ISSUE #385: OP_RETURN starting with"!a" is not found when OP_RETURN  !aĆ[a+UQ{d^½2 is present
**Describe the bug**
There seems to be a bug when looking for an OP_RETURN starting with"!a" . Chainhook returns 0 actions triggered as the OP_RETURN starting with"!a" is not found when OP_RETURN  !aĆ[a+UQ{d^½2 is present

Transaction ID https://mempool.space/tx/6b9736710c061a3cef8c2cdcd46cee433c7df028ac1b71ab96dd388a2309816f
Block#  801219
Time stamp 2023-08-01 10:50

As you can see the blocks are scanned but it cannot find the OP_RETURN starting with "!a"

Screenshot 2023-08-15 at 9 33 43 AM

Here is the OP_RETURN  screen shot below   !aĆ[a+UQ{d^½2 

Screenshot 2023-08-15 at 9 28 20 AM

Here is the predicate where I am looking for OP_RETURNS that start with "!a"

```
{
  "uuid": "1",
  "name": "Hello Ordinals",
  "chain": "bitcoin",
  "version": 1,
  "networks": {
    "mainnet": {
      "start_block": 801220,
      "end_block": 801230,
      "if_this": {
        "scope": "outputs",
        "op_return": {
          "starts_with": "!a"
        }
        },
        "then_that": {
          "file_append": {
            "path": "automate/tests/bitcoin-predicates/OpReturn/OpReturn-file-result.json"
          }
        }
      }
    }
```

### PR DESCRIPTION
**Pull request by qustavo**
### Description

Handles OP_RETURN  predicates correctly.

#### Breaking change?

Potentially yes, but unlikely.
Currently there is a OP_RETURN handler, that matches the `output.script_pubkey` against the expression set in the predicate, although this implementation does not confirm with the documentation, someone might be relying on it

### Checklist

- [x] All tests pass
- [x] Tests added in this PR (if applicable)

fixes #385 #388

### CODE REVIEW

**Comment by qustavo** [comment]
Still a draft, since I'm not so sure if the tests on the PR are the right way to go.

**Comment by qustavo** [comment]
@lgalabru can you have a look at why CI is failing?

**Comment by lgalabru** [comment]
CI is failing because it's being triggered from your fork, that does not have knowledges of the secrets required to push a build to Dockerhub. Safe to ignore!
Feel free to tag reviewers when you think the PR is ready!

**Comment by qustavo** [comment]
For some reason I can't set reviewers, probably a permission issue.
image

**Review by lgalabru — APPROVED** [review]
LGTM!

**Comment by qustavo** [comment]
@lgalabru @MicaiahReid is there anything else left to do for this PR to get merged?

**Comment by lgalabru** [comment]
Done! thank you @qustavo 🙏

**Pull request merged**
